#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef SDKCORE_SWIFT_H
#define SDKCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import Photos;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// App ID Type
typedef SWIFT_ENUM(NSInteger, AppIDType, open) {
  AppIDTypeNone = 0,
  AppIDTypeHdbank = 1,
  AppIDTypeVikki = 2,
};

/// App Key Configuration
SWIFT_CLASS("_TtC7SDKCore12AppKeyConfig")
@interface AppKeyConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
/// Audit NFC Request for logging NFC operations
/// Corresponds to Android AuditNfcRequest.kt
SWIFT_CLASS("_TtC7SDKCore15AuditNfcRequest")
@interface AuditNfcRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Base response model containing common fields shared across all API responses
/// Corresponds to Android BaseResponse abstract class
SWIFT_CLASS("_TtC7SDKCore12BaseResponse")
@interface BaseResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// C06 Configuration
SWIFT_CLASS("_TtC7SDKCore9C06Config")
@interface C06Config : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Check C06 Request model
/// Corresponds to Android CheckC06Request data class
SWIFT_CLASS("_TtC7SDKCore15CheckC06Request")
@interface CheckC06Request : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Check C06 Response model
/// Corresponds to Android CheckC06Response data class
SWIFT_CLASS("_TtC7SDKCore16CheckC06Response")
@interface CheckC06Response : BaseResponse
@end

/// C06 Check Result model
SWIFT_CLASS("_TtCC7SDKCore16CheckC06Response14C06CheckResult")
@interface C06CheckResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Check Face Response model
/// Corresponds to Android CheckFaceResponse data class
SWIFT_CLASS("_TtC7SDKCore17CheckFaceResponse")
@interface CheckFaceResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Face Verify Result model
SWIFT_CLASS("_TtCC7SDKCore17CheckFaceResponse16FaceVerifyResult")
@interface FaceVerifyResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Check Liveness Response model
/// Corresponds to Android CheckLivenessResponse data class
SWIFT_CLASS("_TtC7SDKCore21CheckLivenessResponse")
@interface CheckLivenessResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Metadata model
SWIFT_CLASS("_TtCC7SDKCore21CheckLivenessResponse8Metadata")
@interface Metadata : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Liveness Check Result model
SWIFT_CLASS("_TtCC7SDKCore21CheckLivenessResponse19LivenessCheckResult")
@interface LivenessCheckResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Details model for liveness check
SWIFT_CLASS("_TtCCC7SDKCore21CheckLivenessResponse19LivenessCheckResult7Details")
@interface Details : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Quality Checks model for liveness
SWIFT_CLASS("_TtCCCC7SDKCore21CheckLivenessResponse19LivenessCheckResult7Details13QualityChecks")
@interface QualityChecks : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Check OCR Response model
/// Corresponds to Android CheckOcrResponse data class
SWIFT_CLASS("_TtC7SDKCore16CheckOcrResponse")
@interface CheckOcrResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// OCR Check Result model
SWIFT_CLASS("_TtCC7SDKCore16CheckOcrResponse14OcrCheckResult")
@interface OcrCheckResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Detail model for OCR result
SWIFT_CLASS("_TtCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail")
@interface Detail : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Fields Extracted model
SWIFT_CLASS("_TtCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail15FieldsExtracted")
@interface FieldsExtracted : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// MRZ String model
SWIFT_CLASS("_TtCCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail15FieldsExtracted9MrzString")
@interface MrzString : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Permanent Address model
SWIFT_CLASS("_TtCCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail15FieldsExtracted16PermanentAddress")
@interface PermanentAddress : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Forgery Checks model
SWIFT_CLASS("_TtCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail13ForgeryChecks")
@interface ForgeryChecks : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Quality Checks model
SWIFT_CLASS("_TtCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail13QualityChecks")
@interface QualityChecks : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Tamper Checks model
SWIFT_CLASS("_TtCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail12TamperChecks")
@interface TamperChecks : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Rule Checks model
SWIFT_CLASS("_TtCCCC7SDKCore16CheckOcrResponse14OcrCheckResult6Detail10RuleChecks")
@interface RuleChecks : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Check SDK Request model
/// Corresponds to Android CheckSdkRequest data class
SWIFT_CLASS("_TtC7SDKCore15CheckSdkRequest")
@interface CheckSdkRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Check Summary Response model
/// Corresponds to Android CheckSummaryResponse data class
SWIFT_CLASS("_TtC7SDKCore20CheckSummaryResponse")
@interface CheckSummaryResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Detail model for summary
SWIFT_CLASS("_TtCC7SDKCore20CheckSummaryResponse6Detail")
@interface Detail : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Common field model for confidence, score, and value patterns
/// Corresponds to Android CommonField data class
SWIFT_CLASS("_TtC7SDKCore11CommonField")
@interface CommonField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Extended common field model with additional high/low range fields
/// Corresponds to Android CommonFieldWithRange data class
SWIFT_CLASS("_TtC7SDKCore20CommonFieldWithRange")
@interface CommonFieldWithRange : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// DG13 File Data Model
/// Corresponds to Android DG13File class
/// This class represents Data Group 13 from NFC chip which contains personal information
/// Note: On Android, this uses Bouncy Castle and JMRTD libraries for ASN.1 parsing.
/// On iOS, actual NFC data parsing is handled by the NFC module using CoreNFC.
/// This class serves as a data container for the parsed information.
SWIFT_CLASS("_TtC7SDKCore8DG13File")
@interface DG13File : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// DG13 Information Type Constants
/// Corresponds to Android DG13InfoType companion class
/// These constants define field types in the DG13 data group of NFC chips
SWIFT_CLASS("_TtC7SDKCore12DG13InfoType")
@interface DG13InfoType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Main EKYC Configuration
SWIFT_CLASS("_TtC7SDKCore13EKYCConfigSDK")
@interface EKYCConfigSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// EKYC Error Events - corresponds to Android EKYCErrorEvent enum
typedef SWIFT_ENUM(NSInteger, EKYCErrorEvent, open) {
  EKYCErrorEventSdkStartError = 0,
  EKYCErrorEventErrorUnknown = 1,
  EKYCErrorEventOcrError = 2,
  EKYCErrorEventFaceError = 3,
  EKYCErrorEventLivenessError = 4,
  EKYCErrorEventOcrUnrecognizedIdCard = 100,
  EKYCErrorEventOcrWrongIdCardSide = 101,
  EKYCErrorEventOcrCannotGetIdNumber = 102,
  EKYCErrorEventOcrCannotGetName = 103,
  EKYCErrorEventOcrCannotGetBirthYear = 104,
  EKYCErrorEventOcrCannotGetExpiryDate = 105,
  EKYCErrorEventOcrCannotGetIssueDate = 106,
  EKYCErrorEventOcrCannotGetResidence = 107,
  EKYCErrorEventOcrCannotGetHometown = 108,
  EKYCErrorEventOcrCannotGetGender = 109,
  EKYCErrorEventOcrMissingIdCardPart = 110,
  EKYCErrorEventOcrNotOriginalIdCard = 111,
  EKYCErrorEventOcrIdCardFromOtherDevice = 112,
  EKYCErrorEventOcrCannotRecognizePortrait = 113,
  EKYCErrorEventOcrCutCornerIdCard = 114,
  EKYCErrorEventOcrBlurryIdCard = 115,
  EKYCErrorEventOcrGlareIdCard = 116,
  EKYCErrorEventOcrInvalidIdCard = 117,
  EKYCErrorEventOcrFakeMrz = 118,
  EKYCErrorEventOcrPhotocopyIdCard = 119,
  EKYCErrorEventOcrFontBackNotMatch = 120,
  EKYCErrorEventOcrQrCodeIdMismatch = 121,
  EKYCErrorEventLivenessFail = 200,
  EKYCErrorEventMultipleFacesInSelfie = 201,
  EKYCErrorEventEyesClosedInSelfie = 202,
  EKYCErrorEventMaskPresentInSelfie = 203,
  EKYCErrorEventFaceIsBlurred = 204,
  EKYCErrorEventFaceOccludedInSelfie = 205,
  EKYCErrorEventEyewearDetectedInSelfie = 206,
  EKYCErrorEventHeadIsTurnedInSelfie = 207,
  EKYCErrorEventScanNfcError = 300,
  EKYCErrorEventScanNfcCheck = 301,
  EKYCErrorEventScanNfcEnable = 302,
  EKYCErrorEventC06Error = 303,
  EKYCErrorEventNfcMutualAuthFailed = 304,
  EKYCErrorEventNfcConnectionLost = 305,
  EKYCErrorEventNfcInvalidMrzKey = 306,
  EKYCErrorEventNfcIoError = 307,
  EKYCErrorEventNfcUnknownError = 308,
  EKYCErrorEventNfcUserCancel = 309,
  EKYCErrorEventNfcChipAuthFailed = 310,
  EKYCErrorEventQrcodeError = 400,
  EKYCErrorEventFetchHistoryError = 500,
};

/// EKYC Error Result
SWIFT_CLASS("_TtC7SDKCore15EKYCErrorResult")
@interface EKYCErrorResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Flow không được trùng hoặc rỗng
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EKYCErrorResult * _Nonnull SDK_START_FLOW_ERROR;)
+ (EKYCErrorResult * _Nonnull)SDK_START_FLOW_ERROR SWIFT_WARN_UNUSED_RESULT;
/// SDK Start Error
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EKYCErrorResult * _Nonnull SDK_START_ERROR;)
+ (EKYCErrorResult * _Nonnull)SDK_START_ERROR SWIFT_WARN_UNUSED_RESULT;
/// C06 Error
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EKYCErrorResult * _Nonnull C06_ERROR;)
+ (EKYCErrorResult * _Nonnull)C06_ERROR SWIFT_WARN_UNUSED_RESULT;
/// Unknown Error
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EKYCErrorResult * _Nonnull ERROR_UNKNOWN;)
+ (EKYCErrorResult * _Nonnull)ERROR_UNKNOWN SWIFT_WARN_UNUSED_RESULT;
/// Liveness Error
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EKYCErrorResult * _Nonnull LIVENESS_ERROR;)
+ (EKYCErrorResult * _Nonnull)LIVENESS_ERROR SWIFT_WARN_UNUSED_RESULT;
/// Face Error
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) EKYCErrorResult * _Nonnull FACE_ERROR;)
+ (EKYCErrorResult * _Nonnull)FACE_ERROR SWIFT_WARN_UNUSED_RESULT;
/// Create custom error result
/// Matches Android EKYCErrorResult.createCustom()
+ (EKYCErrorResult * _Nonnull)createCustomWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
/// Get error result from error code
/// Matches Android EKYCErrorResult.fromCode()
+ (EKYCErrorResult * _Nullable)fromCode:(NSString * _Nonnull)code SWIFT_WARN_UNUSED_RESULT;
/// Get error result from details array - matches Android getErrorResultFromDetails()
/// This method formats multiple error details into a single error message
/// \param details Array of CheckSummaryResponse.Detail objects
///
///
/// returns:
/// EKYCErrorResult with combined error messages
+ (EKYCErrorResult * _Nonnull)getErrorResultFromDetails:(NSArray * _Nullable)details SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// EKYC Events - corresponds to Android EKYCEvent enum
typedef SWIFT_ENUM(NSInteger, EKYCEvent, open) {
  EKYCEventSdkStartSuccess = 0,
  EKYCEventSdkEndSuccess = 1,
  EKYCEventScanNfcStart = 2,
  EKYCEventScanNfcSuccess = 3,
  EKYCEventC06Success = 4,
  EKYCEventLivenessSuccess = 5,
  EKYCEventFaceProgress = 6,
  EKYCEventFaceSuccess = 7,
  EKYCEventOcrSuccess = 8,
  EKYCEventQrcodeSuccess = 9,
  EKYCEventFetchLatestTransactionSuccess = 10,
};

/// EKYC State Model
/// Corresponds to Android EkycStateModel data class
/// Holds the complete state of an eKYC transaction
SWIFT_CLASS("_TtC7SDKCore14EkycStateModel")
@interface EkycStateModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// File EKYC Model - holds file URLs for captured images
SWIFT_CLASS("_TtCC7SDKCore14EkycStateModel13FileEKYCModel")
@interface FileEKYCModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class NSData;
/// Utility functions for handling common error patterns in SDK
/// Corresponds to Android ErrorHandlerUtils object
/// Note: Response models will be defined in separate files
SWIFT_CLASS("_TtC7SDKCore17ErrorHandlerUtils")
@interface ErrorHandlerUtils : NSObject
/// Parse Face Service error response
/// \param errorData JSON error response data
///
///
/// returns:
/// Error result object
+ (EKYCErrorResult * _Nonnull)parseFaceErrorResponseWithErrorData:(NSData * _Nullable)errorData SWIFT_WARN_UNUSED_RESULT;
/// Parse C06 error response
/// \param errorData JSON error response data
///
///
/// returns:
/// Error result object
+ (EKYCErrorResult * _Nonnull)parseC06ErrorResponseWithErrorData:(NSData * _Nullable)errorData SWIFT_WARN_UNUSED_RESULT;
/// Parse OCR error response and extract error message from details
/// \param errorData JSON error response data
///
///
/// returns:
/// Error result object
+ (EKYCErrorResult * _Nonnull)parseOcrErrorResponseWithErrorData:(NSData * _Nullable)errorData SWIFT_WARN_UNUSED_RESULT;
/// Parse Liveness error response and extract error message from details
/// \param errorData JSON error response data
///
///
/// returns:
/// Error result object
+ (EKYCErrorResult * _Nonnull)parseLivenessErrorResponseWithErrorData:(NSData * _Nullable)errorData SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Face Service Configuration
SWIFT_CLASS("_TtC7SDKCore17FaceServiceConfig")
@interface FaceServiceConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Face State Types - corresponds to Android FaceStateType enum
/// Defines the different face states/gestures used in liveness detection
typedef SWIFT_ENUM(NSInteger, FaceStateType, open) {
  FaceStateTypeNoFace = 0,
  FaceStateTypeSmile = 1,
  FaceStateTypeUp = 2,
  FaceStateTypeDown = 3,
  FaceStateTypeLeft = 4,
  FaceStateTypeRight = 5,
  FaceStateTypeSmash = 6,
  FaceStateTypeStraight = 7,
};

@class NSURL;
/// Utility class for file operations in SDK modules
/// Corresponds to Android FileUtils object
SWIFT_CLASS("_TtC7SDKCore9FileUtils")
@interface FileUtils : NSObject
/// Create output file for OCR capture
///
/// returns:
/// URL for OCR image file
+ (NSURL * _Nonnull)createOcrOutputFile SWIFT_WARN_UNUSED_RESULT;
/// Create output file for Face capture
///
/// returns:
/// URL for Face image file
+ (NSURL * _Nonnull)createFaceOutputFile SWIFT_WARN_UNUSED_RESULT;
/// Create output file for Liveness capture
///
/// returns:
/// URL for Liveness image file
+ (NSURL * _Nonnull)createLivenessOutputFile SWIFT_WARN_UNUSED_RESULT;
/// Create output file for QR Code capture
///
/// returns:
/// URL for QR Code image file
+ (NSURL * _Nonnull)createQrCodeOutputFile SWIFT_WARN_UNUSED_RESULT;
/// Create output file for NFC capture
///
/// returns:
/// URL for NFC image file
+ (NSURL * _Nonnull)createNfcOutputFile SWIFT_WARN_UNUSED_RESULT;
/// Generic method to create output file with custom prefix
/// \param prefix File name prefix
///
/// \param subDirectory Optional subdirectory name
///
///
/// returns:
/// URL for the created file
+ (NSURL * _Nonnull)createOutputFileWithPrefix:(NSString * _Nonnull)prefix subDirectory:(NSString * _Nullable)subDirectory SWIFT_WARN_UNUSED_RESULT;
/// Delete all camera-related folders and their contents
///
/// returns:
/// true if all folders were deleted successfully, false otherwise
+ (BOOL)deleteAllCameraFolders SWIFT_WARN_UNUSED_RESULT;
/// Delete a specific camera folder and its contents
/// \param folderName Name of the folder to delete (Ocr, Face, Liveness, QRCode, NFC)
///
///
/// returns:
/// true if folder was deleted successfully, false otherwise
+ (BOOL)deleteCameraFolderWithFolderName:(NSString * _Nonnull)folderName SWIFT_WARN_UNUSED_RESULT;
/// Get total size of all camera folders in bytes
///
/// returns:
/// Total size in bytes
+ (int64_t)getTotalCameraFoldersSize SWIFT_WARN_UNUSED_RESULT;
/// Get list of all camera folders with their sizes
///
/// returns:
/// Dictionary of folder names to their sizes in bytes
+ (NSDictionary<NSString *, NSNumber *> * _Nonnull)getCameraFoldersInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;
/// Image utility functions
/// Corresponds to Android ImageUtils object
SWIFT_CLASS("_TtC7SDKCore10ImageUtils")
@interface ImageUtils : NSObject
/// Save base64 encoded image to temporary file
/// \param base64Image Base64 encoded image string (with or without data URI prefix)
///
///
/// returns:
/// Path to the saved file, or empty string if failed
+ (NSString * _Nonnull)saveBase64ImageToTempFileWithBase64Image:(NSString * _Nullable)base64Image SWIFT_WARN_UNUSED_RESULT;
/// Convert UIImage to base64 string
/// \param image UIImage to convert
///
/// \param compressionQuality JPEG compression quality (0.0 to 1.0)
///
///
/// returns:
/// Base64 encoded string, or nil if conversion fails
+ (NSString * _Nullable)imageToBase64WithImage:(UIImage * _Nonnull)image compressionQuality:(CGFloat)compressionQuality SWIFT_WARN_UNUSED_RESULT;
/// Convert Data to base64 string
/// \param data Image data
///
///
/// returns:
/// Base64 encoded string
+ (NSString * _Nonnull)dataToBase64WithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// Load image from base64 string
/// \param base64String Base64 encoded image string
///
///
/// returns:
/// UIImage if successful, nil otherwise
+ (UIImage * _Nullable)imageFromBase64WithBase64String:(NSString * _Nullable)base64String SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Liveness Configuration
SWIFT_CLASS("_TtC7SDKCore14LivenessConfig")
@interface LivenessConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Message model for SDK responses
/// Corresponds to Android Message data class
SWIFT_CLASS("_TtC7SDKCore7Message")
@interface Message : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Error Messages - corresponds to Android MessageError object
/// Contains localized error messages for various SDK validation errors
SWIFT_CLASS("_TtC7SDKCore12MessageError")
@interface MessageError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// NFC Data Model
/// Corresponds to Android NFCData class
/// Contains all information extracted from NFC chip
SWIFT_CLASS("_TtC7SDKCore7NFCData")
@interface NFCData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Native Configuration - corresponds to Android NativeConfig object
/// Configuration values are now loaded from OptionConfig at runtime
SWIFT_CLASS("_TtC7SDKCore12NativeConfig")
@interface NativeConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NativeConfig * _Nonnull shared;)
+ (NativeConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Get base URL
/// Returns APIGW URL from OptionConfig environment (all APIs use APIGW)
- (NSString * _Nonnull)getBaseURL SWIFT_WARN_UNUSED_RESULT;
/// Get base API URL
/// Returns API URL from OptionConfig environment (for BackOffice APIs)
- (NSString * _Nonnull)getBaseURLApi SWIFT_WARN_UNUSED_RESULT;
/// Get API Gateway URL
/// Returns apigwURL from OptionConfig environment
- (NSString * _Nonnull)getApigwURL SWIFT_WARN_UNUSED_RESULT;
/// Set base URL (for runtime configuration override)
- (void)setBaseURL:(NSString * _Nonnull)url;
/// Set base API URL (for runtime configuration override)
- (void)setBaseURLApi:(NSString * _Nonnull)url;
/// Reset configuration and reload from native library
- (void)resetConfiguration;
@end

/// NFC Configuration
SWIFT_CLASS("_TtC7SDKCore9NfcConfig")
@interface NfcConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class QRCodeData;
/// Helper functions for NFC operations
/// Corresponds to Android NfcHelper object
SWIFT_CLASS("_TtC7SDKCore9NfcHelper")
@interface NfcHelper : NSObject
/// Create NFC configuration from MRZ data
/// \param idNumber Document ID number from MRZ
///
/// \param dateOfBirth Date of birth in dd-MM-yyyy format
///
/// \param dateOfExpiry Expiry date in dd-MM-yyyy format
///
/// \param transactionId Transaction ID
///
/// \param documentNumberOld Optional old document number
///
/// \param qrCodeData Optional QR code data for filling missing NFC fields
///
///
/// returns:
/// NfcConfig object, or nil if creation fails
+ (NfcConfig * _Nullable)createNfcConfigWithIdNumber:(NSString * _Nullable)idNumber dateOfBirth:(NSString * _Nullable)dateOfBirth dateOfExpiry:(NSString * _Nullable)dateOfExpiry transactionId:(NSString * _Nonnull)transactionId documentNumberOld:(NSString * _Nullable)documentNumberOld qrCodeData:(QRCodeData * _Nullable)qrCodeData SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// NFC Info Model
/// Corresponds to Android NfcInfo class
/// Contains raw data groups from NFC chip
SWIFT_CLASS("_TtC7SDKCore7NfcInfo")
@interface NfcInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// OCR Configuration
SWIFT_CLASS("_TtC7SDKCore9OcrConfig")
@interface OcrConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Option Configuration
SWIFT_CLASS("_TtC7SDKCore12OptionConfig")
@interface OptionConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Utility for checking and requesting permissions
/// Corresponds to Android PermissionUtils object
/// Note: iOS permission handling is different from Android
SWIFT_CLASS("_TtC7SDKCore15PermissionUtils")
@interface PermissionUtils : NSObject
/// Check if camera permission is granted
///
/// returns:
/// true if camera permission is granted, false otherwise
+ (BOOL)isCameraGranted SWIFT_WARN_UNUSED_RESULT;
/// Check camera permission status
///
/// returns:
/// Authorization status
+ (AVAuthorizationStatus)cameraAuthorizationStatus SWIFT_WARN_UNUSED_RESULT;
/// Request camera permission
/// \param completion Callback with result (true if granted, false otherwise)
///
+ (void)requestCameraPermissionWithCompletion:(void (^ _Nonnull)(BOOL))completion;
/// Check if photo library permission is granted
///
/// returns:
/// true if photo library permission is granted, false otherwise
+ (BOOL)isPhotoLibraryGranted SWIFT_WARN_UNUSED_RESULT;
/// Check photo library permission status
///
/// returns:
/// Authorization status
+ (PHAuthorizationStatus)photoLibraryAuthorizationStatus SWIFT_WARN_UNUSED_RESULT;
/// Request photo library permission
/// \param completion Callback with result (true if granted, false otherwise)
///
+ (void)requestPhotoLibraryPermissionWithCompletion:(void (^ _Nonnull)(BOOL))completion;
/// Check if a specific permission is granted
/// \param permission Permission type
///
///
/// returns:
/// true if granted, false otherwise
+ (BOOL)isPermissionGrantedWithPermission:(NSString * _Nonnull)permission SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// QR Code Data Model
/// Stores parsed QR code information from ID card
SWIFT_CLASS("_TtC7SDKCore10QRCodeData")
@interface QRCodeData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// SDK API Codes - corresponds to Android SDKApiCode enum
/// Defines the different API endpoints/operations in the eKYC system
typedef SWIFT_ENUM(NSInteger, SDKApiCode, open) {
  SDKApiCodeSdkNfc = 0,
  SDKApiCodeFaceCompare = 1,
  SDKApiCodeLivenessCheckServer = 2,
  SDKApiCodeOcrNationalId = 3,
};

/// SDK Base Response - used for simple API responses
/// Corresponds to Android SDKBaseResponse data class
SWIFT_CLASS("_TtC7SDKCore15SDKBaseResponse")
@interface SDKBaseResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK Base ViewModel
/// Corresponds to Android SDKBaseViewModel class
/// Provides base functionality for all SDK ViewModels
/// Note: iOS uses Combine framework instead of Android’s LiveData and Coroutines
SWIFT_CLASS("_TtC7SDKCore16SDKBaseViewModel")
@interface SDKBaseViewModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Cancel a specific task by key
/// \param key The task key to cancel
///
- (void)cancelTaskWithKey:(NSString * _Nonnull)key;
/// Check if a task is running
/// \param key The task key to check
///
///
/// returns:
/// true if task is active, false otherwise
- (BOOL)isTaskRunningWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Cancel all running tasks
- (void)cancelAllTasks;
@end

/// SDK Bundle Event Keys - corresponds to Android SDKBundleEvent object
/// Contains keys for passing data between SDK components
SWIFT_CLASS("_TtC7SDKCore14SDKBundleEvent")
@interface SDKBundleEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK EKYC Result model
/// Corresponds to Android SDKEkycResult data class
/// This model aggregates results from all eKYC operations:
/// <ul>
///   <li>
///     OCR (ID card scanning)
///   </li>
///   <li>
///     Liveness check
///   </li>
///   <li>
///     Face comparison
///   </li>
///   <li>
///     NFC reading
///   </li>
///   <li>
///     C06 residence verification
///   </li>
/// </ul>
SWIFT_CLASS("_TtC7SDKCore13SDKEkycResult")
@interface SDKEkycResult : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Custom description for debugging
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// SDK API Endpoints
/// Centralized location for all API endpoints
SWIFT_CLASS("_TtC7SDKCore12SDKEndpoints")
@interface SDKEndpoints : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// SDK Environment Type
typedef SWIFT_ENUM(NSInteger, SDKEnvironment, open) {
  SDKEnvironmentDev = 0,
  SDKEnvironmentProd = 1,
};

/// SDK Image Result Model
/// Corresponds to Android SDKImageResultModel data class
SWIFT_CLASS("_TtC7SDKCore19SDKImageResultModel")
@interface SDKImageResultModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK Job Types - corresponds to Android SDKJobType object
/// Defines the different background job types for SDK operations
SWIFT_CLASS("_TtC7SDKCore10SDKJobType")
@interface SDKJobType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK List Transaction Response model
/// Corresponds to Android SDKListTransactionResponse data class
SWIFT_CLASS("_TtC7SDKCore26SDKListTransactionResponse")
@interface SDKListTransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Result Wrapper model
SWIFT_CLASS("_TtCC7SDKCore26SDKListTransactionResponse13ResultWrapper")
@interface ResultWrapper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Details model
SWIFT_CLASS("_TtCCC7SDKCore26SDKListTransactionResponse13ResultWrapper7Details")
@interface Details : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Transactions model
SWIFT_CLASS("_TtCCCC7SDKCore26SDKListTransactionResponse13ResultWrapper7Details12Transactions")
@interface Transactions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK Response Key Constants - corresponds to Android SDKResponseKey object
/// Contains constants for parsing and validating API responses
SWIFT_CLASS("_TtC7SDKCore14SDKResponseKey")
@interface SDKResponseKey : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK Step Types - corresponds to Android SDKStepType enum
/// Defines the different steps in the eKYC workflow
typedef SWIFT_ENUM(NSInteger, SDKStepType, open) {
  SDKStepTypeOcrFront = 0,
  SDKStepTypeOcrBack = 1,
  SDKStepTypeQrCode = 2,
  SDKStepTypeNfc = 3,
  SDKStepTypeLiveness = 4,
  SDKStepTypeResult = 5,
};

/// SDK Transaction Response model
/// Corresponds to Android SDKTransactionResponse data class
SWIFT_CLASS("_TtC7SDKCore22SDKTransactionResponse")
@interface SDKTransactionResponse : BaseResponse
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// SDK Types - corresponds to Android SDKType enum
typedef SWIFT_ENUM(NSInteger, SDKType, open) {
  SDKTypeNfc = 0,
  SDKTypeOcr = 1,
  SDKTypeLiveness = 2,
  SDKTypeQrCode = 3,
  SDKTypeC06 = 4,
  SDKTypeFaceService = 5,
};

/// General utility functions
SWIFT_CLASS("_TtC7SDKCore8SDKUtils")
@interface SDKUtils : NSObject
/// Check if string is null or empty
+ (BOOL)isStringEmpty:(NSString * _Nullable)string SWIFT_WARN_UNUSED_RESULT;
/// Check if string is not null and not empty
+ (BOOL)isStringNotEmpty:(NSString * _Nullable)string SWIFT_WARN_UNUSED_RESULT;
/// Check if dictionary is null or empty
+ (BOOL)isDictionaryEmpty:(NSDictionary * _Nullable)dict SWIFT_WARN_UNUSED_RESULT;
/// Check if dictionary is not null and not empty
+ (BOOL)isDictionaryNotEmpty:(NSDictionary * _Nullable)dict SWIFT_WARN_UNUSED_RESULT;
/// Check if array is null or empty
+ (BOOL)isArrayEmpty:(NSArray * _Nullable)array SWIFT_WARN_UNUSED_RESULT;
/// Check if array is not null and not empty
+ (BOOL)isArrayNotEmpty:(NSArray * _Nullable)array SWIFT_WARN_UNUSED_RESULT;
/// Format date from dd-mm-yyyy to dd/mm/yyyy for OCR display (matching NFC format)
/// \param dateString Date string in dd-mm-yyyy format
///
///
/// returns:
/// Formatted date string in dd/mm/yyyy format, or original string if empty
+ (NSString * _Nonnull)formatDateForOCR:(NSString * _Nonnull)dateString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Core SDK Configuration Manager - corresponds to Android SdkEkycCore
SWIFT_CLASS("_TtC7SDKCore11SdkEkycCore")
@interface SdkEkycCore : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SdkEkycCore * _Nonnull shared;)
+ (SdkEkycCore * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) EKYCConfigSDK * _Nonnull ekycConfigSDK;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Set (override) entire configuration
- (void)setConfig:(EKYCConfigSDK * _Nonnull)newConfig;
/// Update configuration (merge non-nil fields)
- (void)updateConfig:(EKYCConfigSDK * _Nonnull)newConfig;
/// Reset configuration to default
- (void)resetConfig;
@end

/// Style Configuration
SWIFT_CLASS("_TtC7SDKCore11StyleConfig")
@interface StyleConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Text Style Configuration
SWIFT_CLASS("_TtCC7SDKCore11StyleConfig9TextStyle")
@interface TextStyle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
